import 'models.dart';

final mockUsers = [
  User(
    id: 'user_1',
    name: 'Rahim Ahmed',
    email: 'rahim@example.com',
    phone: '01711223344',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rahim',
    bio: 'Property owner with 5+ years experience',
    createdAt: DateTime(2023, 1, 15),
    isVerified: true,
    rating: 4.8,
    reviewCount: 24,
  ),
  User(
    id: 'user_2',
    name: 'Fatema Begum',
    email: 'fatema@example.com',
    phone: '01811223344',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatema',
    bio: 'Trusted landlord in Dhanmondi area',
    createdAt: DateTime(2022, 6, 20),
    isVerified: true,
    rating: 4.9,
    reviewCount: 18,
  ),
  User(
    id: 'user_3',
    name: 'Karim Hassan',
    email: 'karim@example.com',
    phone: '01911223344',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karim',
    bio: 'Managing multiple rental properties',
    createdAt: DateTime(2023, 3, 10),
    isVerified: false,
    rating: 4.5,
    reviewCount: 12,
  ),
  User(
    id: 'user_4',
    name: 'Salma Khan',
    email: 'salma@example.com',
    phone: '01611223344',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=salma',
    bio: 'New property owner',
    createdAt: DateTime(2024, 1, 5),
    isVerified: false,
    rating: 4.2,
    reviewCount: 5,
  ),
];