import 'enums.dart';
import 'location.dart';
import 'mock_users.dart';
import 'property.dart';

// Shared mock location objects used across properties
const _dhaka = Division(id: 1, nameEn: 'Dhaka', nameBn: 'ঢাকা');
const _chittagong = Division(id: 2, nameEn: 'Chittagong', nameBn: 'চট্টগ্রাম');
const _sylhet = Division(id: 6, nameEn: 'Sylhet', nameBn: 'সিলেট');

final _mockLocations = {
  'dhanmondi': const Location(
    division: _dhaka,
    district: District(id: 1, divisionId: 1, nameEn: 'Dhaka', nameBn: 'ঢাকা'),
    thana: Thana(id: 1, districtId: 1, nameEn: 'Dhanmondi', nameBn: 'ধানমন্ডি'),
    area: Area(id: 1, thanaId: 1, nameEn: 'Dhaka University Area', nameBn: 'ঢাকা বিশ্ববিদ্যালয় এলাকা'),
    areaNameEn: 'Dhaka University Area',
    areaNameBn: 'ঢাকা বিশ্ববিদ্যালয় এলাকা',
    latitude: 23.7403,
    longitude: 90.3760,
  ),
  'gulshan': const Location(
    division: _dhaka,
    district: District(id: 1, divisionId: 1, nameEn: 'Dhaka', nameBn: 'ঢাকা'),
    thana: Thana(id: 2, districtId: 1, nameEn: 'Gulshan', nameBn: 'গুলশান'),
    areaNameEn: 'Gulshan-2',
    areaNameBn: 'গুলশান-২',
    latitude: 23.7925,
    longitude: 90.4126,
  ),
  'banani': const Location(
    division: _dhaka,
    district: District(id: 1, divisionId: 1, nameEn: 'Dhaka', nameBn: 'ঢাকা'),
    thana: Thana(id: 3, districtId: 1, nameEn: 'Banani', nameBn: 'বনানী'),
    areaNameEn: 'Banani Model Town',
    areaNameBn: 'বনানী মডেল টাউন',
    latitude: 23.7937,
    longitude: 90.4066,
  ),
  'uttara': const Location(
    division: _dhaka,
    district: District(id: 1, divisionId: 1, nameEn: 'Dhaka', nameBn: 'ঢাকা'),
    thana: Thana(id: 4, districtId: 1, nameEn: 'Uttara', nameBn: 'উত্তরা'),
    areaNameEn: 'Uttara Sector 7',
    areaNameBn: 'উত্তরা সেক্টর ৭',
    latitude: 23.8759,
    longitude: 90.3795,
  ),
  'mirpur': const Location(
    division: _dhaka,
    district: District(id: 1, divisionId: 1, nameEn: 'Dhaka', nameBn: 'ঢাকা'),
    thana: Thana(id: 5, districtId: 1, nameEn: 'Mirpur', nameBn: 'মিরপুর'),
    areaNameEn: 'Mirpur-10',
    areaNameBn: 'মিরপুর-১০',
    latitude: 23.8069,
    longitude: 90.3687,
  ),
  'khlushi': const Location(
    division: _chittagong,
    district: District(id: 5, divisionId: 2, nameEn: 'Chittagong', nameBn: 'চট্টগ্রাম'),
    thana: Thana(id: 14, districtId: 5, nameEn: 'Khulshi', nameBn: 'খুলশি'),
    areaNameEn: 'Khulshi Residential Area',
    areaNameBn: 'খুলশি আবাসিক এলাকা',
    latitude: 22.3689,
    longitude: 91.8178,
  ),
  'sylhet_zindabazar': const Location(
    division: _sylhet,
    district: District(id: 13, divisionId: 6, nameEn: 'Sylhet', nameBn: 'সিলেট'),
    thana: Thana(id: 100, districtId: 13, nameEn: 'Zindabazar', nameBn: 'জিন্দাবাজার'),
    areaNameEn: 'Zindabazar Main Road',
    areaNameBn: 'জিন্দাবাজার প্রধান রোড',
    latitude: 24.8949,
    longitude: 91.8687,
  ),
};

List<String> _images(String seed, [int count = 3]) {
  return List.generate(
    count,
    (i) => 'https://picsum.photos/seed/${seed}${i}/800/600',
  );
}

final mockProperties = [
  Property(
    id: 'prop_001',
    titleEn: '2 Bedroom Family Apartment in Dhanmondi',
    titleBn: 'ধানমন্ডিতে ২ বেডরুম পারিবারিক অ্যাপার্টমেন্ট',
    descriptionEn:
        'Beautiful family apartment on the 4th floor. Fully furnished living room, separate dining area, gas, all modern amenities.',
    descriptionBn:
        '৪র্থ তলায় সুন্দর পারিবারিক অ্যাপার্টমেন্ট। সম্পূর্ণ সজ্জিত ড্রয়িং রুম, আলাদা ডাইনিং এরিয়া, গ্যাস, সব আধুনিক সুবিধা।',
    price: 25000,
    type: PropertyType.apartment,
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1100,
    images: _images('prop1'),
    location: _mockLocations['dhanmondi']!,
    owner: mockUsers[0],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 7, 20),
    updatedAt: DateTime(2026, 7, 20),
    isFeatured: true,
    amenities: {
      'furnished': true,
      'parking': true,
      'cctv': true,
      'wifi': true,
    },
  ),
  Property(
    id: 'prop_002',
    titleEn: '3 Bedroom Penthouse Apartment in Gulshan',
    titleBn: 'গুলশানে ৩ বেডরুম পেন্টহাউস অ্যাপার্টমেন্ট',
    descriptionEn:
        'Luxury penthouse with rooftop access. Modern kitchen, 3 balconies, panoramic city view. Perfect for families.',
    descriptionBn:
        'ছাদে প্রবেশসহ বিলাসবহুল পেন্টহাউস। আধুনিক রান্নাঘর, ৩টি ব্যালকনি, শহরের প্যানোরামিক দৃশ্য। পরিবারের জন্য উপযুক্ত।',
    price: 65000,
    type: PropertyType.apartment,
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1800,
    images: _images('prop2'),
    location: _mockLocations['gulshan']!,
    owner: mockUsers[1],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 8, 1),
    updatedAt: DateTime(2026, 8, 1),
    isFeatured: true,
    amenities: {
      'furnished': true,
      'parking': true,
      'cctv': true,
      'gym': true,
      'elevator': true,
    },
  ),
  Property(
    id: 'prop_003',
    titleEn: 'Spacious 4 Bedroom House in Banani',
    titleBn: 'বনানীতে প্রশস্ত ৪ বেডরুমের বাসা',
    descriptionEn: 'Duplex house with small garden, servant quarter, and 2-car garage. Very peaceful neighborhood.',
    descriptionBn: 'ছোট বাগান, কর্মচারী কোয়ার্টার এবং ২ গাড়ির গ্যারেজসহ ডুপ্লেক্স বাসা। খুবই শান্ত এলাকা।',
    price: 80000,
    type: PropertyType.house,
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 2500,
    images: _images('prop3'),
    location: _mockLocations['banani']!,
    owner: mockUsers[2],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 7, 15),
    updatedAt: DateTime(2026, 7, 15),
    isFeatured: true,
    amenities: {
      'furnished': false,
      'parking': true,
      'cctv': true,
      'garden': true,
    },
  ),
  Property(
    id: 'prop_004',
    titleEn: '1 Bedroom Studio Apartment in Uttara',
    titleBn: 'উত্তরায় ১ বেডরুম স্টুডিও অ্যাপার্টমেন্ট',
    descriptionEn: 'Compact studio apartment ideal for bachelors or newly married couples. 5 min walk to Metro rail.',
    descriptionBn: 'ব্যাচেলর বা নবদম্পতির জন্য উপযুক্ত কম্প্যাক্ট স্টুডিও অ্যাপার্টমেন্ট। মেট্রো রেল থেকে ৫ মিনিট হাঁটা।',
    price: 12000,
    type: PropertyType.apartment,
    bedrooms: 1,
    bathrooms: 1,
    areaSqft: 500,
    images: _images('prop4'),
    location: _mockLocations['uttara']!,
    owner: mockUsers[3],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 6, 25),
    updatedAt: DateTime(2026, 6, 25),
    amenities: {
      'wifi': true,
      'cctv': true,
    },
  ),
  Property(
    id: 'prop_005',
    titleEn: '3 Bedroom Flat in Mirpur-10',
    titleBn: 'মিরপুর-১০ এ ৩ বেডরুম ফ্ল্যাট',
    descriptionEn: 'Semi-furnished flat with community hall membership and kids play area. Near shopping malls.',
    descriptionBn: 'আধা-সজ্জিত ফ্ল্যাট যেখানে কমিউনিটি হল সদস্যপদ এবং বাচ্চাদের খেলার জায়গা রয়েছে। মার্কেটের কাছে।',
    price: 18000,
    type: PropertyType.apartment,
    bedrooms: 3,
    bathrooms: 2,
    areaSqft: 1200,
    images: _images('prop5'),
    location: _mockLocations['mirpur']!,
    owner: mockUsers[0],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 8, 5),
    updatedAt: DateTime(2026, 8, 5),
    amenities: {
      'parking': true,
      'wifi': true,
      'elevator': true,
    },
  ),
  Property(
    id: 'prop_006',
    titleEn: 'Office Space for Lease in Gulshan-2',
    titleBn: 'গুলশান-২ এ লিজের জন্য অফিস স্পেস',
    descriptionEn: 'Grade-A office space on ground floor with reception area and 4 meeting rooms.',
    descriptionBn: 'গ্রাউন্ড ফ্লোরে গ্রেড-এ অফিস স্পেস যেখানে রিসেপশন এলাকা এবং ৪টি মিটিং রুম রয়েছে।',
    price: 120000,
    type: PropertyType.commercial,
    bedrooms: 0,
    bathrooms: 2,
    areaSqft: 2000,
    images: _images('prop6'),
    location: _mockLocations['gulshan']!,
    owner: mockUsers[1],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 7, 30),
    updatedAt: DateTime(2026, 7, 30),
    isFeatured: true,
    amenities: {
      'parking': true,
      'cctv': true,
      'elevator': true,
      'ac': true,
    },
  ),
  Property(
    id: 'prop_007',
    titleEn: 'Family House in Khulshi, Chittagong',
    titleBn: 'চট্টগ্রামের খুলশিতে পারিবারিক বাসা',
    descriptionEn: '2-storied house with 4 bedrooms, large veranda, and backup generator. Close to colleges.',
    descriptionBn: '৪ বেডরুম, বড় ভেরান্ডা এবং ব্যাকআপ জেনারেটরসহ ২ তলা বাসা। কলেজগুলোর কাছে।',
    price: 30000,
    type: PropertyType.house,
    bedrooms: 4,
    bathrooms: 3,
    areaSqft: 2000,
    images: _images('prop7'),
    location: _mockLocations['khlushi']!,
    owner: mockUsers[2],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 5, 10),
    updatedAt: DateTime(2026, 5, 10),
    amenities: {
      'parking': true,
      'cctv': true,
      'generator': true,
    },
  ),
  Property(
    id: 'prop_008',
    titleEn: 'Budget Room in Dhanmondi',
    titleBn: 'ধানমন্ডিতে বাজেট রুম',
    descriptionEn: 'Single room with attached bath, ideal for students. Sharing kitchen available.',
    descriptionBn: 'সংযুক্ত বাথসহ একক রুম, শিক্ষার্থীদের জন্য আদর্শ। শেয়ারিং রান্নাঘর উপলব্ধ।',
    price: 4500,
    type: PropertyType.room,
    bedrooms: 1,
    bathrooms: 1,
    areaSqft: 180,
    images: _images('prop8'),
    location: _mockLocations['dhanmondi']!,
    owner: mockUsers[3],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 8, 10),
    updatedAt: DateTime(2026, 8, 10),
    amenities: {
      'wifi': true,
    },
  ),
  Property(
    id: 'prop_009',
    titleEn: 'Roof Tile Flat in Sylhet Zindabazar',
    titleBn: 'সিলেট জিন্দাবাজারে রুফ টাইল ফ্ল্যাট',
    descriptionEn: 'Hillside flat with scenic view, 2 bedrooms, and beautiful tiled ceiling.',
    descriptionBn: 'মনোরম দৃশ্যসহ পাহাড়ি ফ্ল্যাট, ২ বেডরুম এবং সুন্দর টালির ছাদ।',
    price: 15000,
    type: PropertyType.apartment,
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 950,
    images: _images('prop9'),
    location: _mockLocations['sylhet_zindabazar']!,
    owner: mockUsers[0],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 6, 1),
    updatedAt: DateTime(2026, 6, 1),
    amenities: {
      'cctv': true,
    },
  ),
  Property(
    id: 'prop_010',
    titleEn: 'Open Land for Sale in Uttara',
    titleBn: 'উত্তরায় বিক্রয়ের জন্য খোলা জমি',
    descriptionEn: '6 katha commercial land with electric and gas connection nearby. Cleared and registered.',
    descriptionBn: 'বৈদ্যুতিক ও গ্যাস সংযোগসহ ৬ কাঠা বাণিজ্যিক জমি। পরিষ্কার এবং রেজিস্টার্ড।',
    price: 1500000,
    type: PropertyType.land,
    bedrooms: 0,
    bathrooms: 0,
    areaSqft: 3960,
    images: _images('prop10'),
    location: _mockLocations['uttara']!,
    owner: mockUsers[1],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 7, 1),
    updatedAt: DateTime(2026, 7, 1),
    isFeatured: true,
  ),
  Property(
    id: 'prop_011',
    titleEn: '5 Bedroom Luxury Home in Banani DOHS',
    titleBn: 'বনানী ডিওএইচএসে ৫ বেডরুম বিলাসবহুল বাড়ি',
    descriptionEn: 'Grand residence with security, backup generator, staff quarters and large garden.',
    descriptionBn: 'নিরাপত্তা, ব্যাকআপ জেনারেটর, কর্মচারী কোয়ার্টার এবং বড় বাগানসহ গ্র্যান্ড বাসভবন।',
    price: 95000,
    type: PropertyType.house,
    bedrooms: 5,
    bathrooms: 5,
    areaSqft: 3200,
    images: _images('prop11'),
    location: _mockLocations['banani']!,
    owner: mockUsers[2],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 4, 18),
    updatedAt: DateTime(2026, 4, 18),
    amenities: {
      'furnished': true,
      'parking': true,
      'cctv': true,
      'generator': true,
      'garden': true,
    },
  ),
  Property(
    id: 'prop_012',
    titleEn: 'Students Hostel in Dhanmondi',
    titleBn: 'ধানমন্ডিতে শিক্ষার্থী হোস্টেল',
    descriptionEn: 'Fully furnished hostel for boys with meal service and study room. Warden on site.',
    descriptionBn: 'খাবার সেবা এবং পড়ার কক্ষসহ ছেলেদের জন্য সম্পূর্ণ সজ্জিত হোস্টেল। তত্ত্বাবধায়ক উপস্থিত।',
    price: 6000,
    type: PropertyType.hostel,
    bedrooms: 1,
    bathrooms: 1,
    areaSqft: 120,
    images: _images('prop12'),
    location: _mockLocations['dhanmondi']!,
    owner: mockUsers[3],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 8, 3),
    updatedAt: DateTime(2026, 8, 3),
    amenities: {
      'wifi': true,
      'meal': true,
    },
  ),
  Property(
    id: 'prop_013',
    titleEn: 'New 2 Bedroom Flat in Mirpur DOHS',
    titleBn: 'মিরপুর ডিওএইচএসে নতুন ২ বেডরুম ফ্ল্যাট',
    descriptionEn: 'Newly built modern flat with all facilities. 24/7 security and dual lift.',
    descriptionBn: 'সব সুবিধাসহ নবনির্মিত আধুনিক ফ্ল্যাট। ২৪/৭ নিরাপত্তা এবং দ্বৈত লিফট।',
    price: 20000,
    type: PropertyType.apartment,
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1150,
    images: _images('prop13'),
    location: _mockLocations['mirpur']!,
    owner: mockUsers[0],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 8, 8),
    updatedAt: DateTime(2026, 8, 8),
    amenities: {
      'parking': true,
      'cctv': true,
      'elevator': true,
    },
  ),
  Property(
    id: 'prop_014',
    titleEn: 'Single Bedroom Flat in Khulshi',
    titleBn: 'খুলশিতে এক বেডরুম ফ্ল্যাট',
    descriptionEn: 'Compact 1-bedroom flat ideal for small families. Near market and bus stop.',
    descriptionBn: 'ছোট পরিবারের জন্য আদর্শ কম্প্যাক্ট ১-বেডরুম ফ্ল্যাট। মার্কেট এবং বাস স্টপের কাছে।',
    price: 8000,
    type: PropertyType.apartment,
    bedrooms: 1,
    bathrooms: 1,
    areaSqft: 550,
    images: _images('prop14'),
    location: _mockLocations['khlushi']!,
    owner: mockUsers[1],
    status: PropertyStatus.active,
    createdAt: DateTime(2026, 7, 22),
    updatedAt: DateTime(2026, 7, 22),
    amenities: {
      'wifi': true,
    },
  ),
];

// Helper to find a property by id (used by detail screen later)
Property? findMockPropertyById(String id) {
  for (final p in mockProperties) {
    if (p.id == id) return p;
  }
  return null;
}